# Generated by Django 4.2.14 on 2025-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('monthly_salary', models.IntegerField()),
                ('approved_limit', models.IntegerField(default=0)),
                ('current_debt', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
